// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {manualreview} from '../models';
import {main} from '../models';
import {updater} from '../models';

export function AddDependency(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AddEndpointMounts(arg1:string,arg2:Array<string>):Promise<void>;

export function ApplyHostResolution(arg1:string,arg2:manualreview.ResolvedEnvelope,arg3:manualreview.ResolvedPayload,arg4:number):Promise<boolean>;

export function ApplyHostResolutionDetailed(arg1:string,arg2:manualreview.ResolvedEnvelope,arg3:manualreview.ResolvedPayload,arg4:number):Promise<main.HostResolutionOutcome>;

export function ApproveManualReview(arg1:string,arg2:string):Promise<void>;

export function AttachToActiveSession(arg1:string):Promise<main.AttachmentSummary>;

export function AttachmentInlineBytes(arg1:string,arg2:number):Promise<Array<number>>;

export function BrowseForAttachment():Promise<string>;

export function BrowseForFolder(arg1:string):Promise<string>;

export function BrowseForSkillFile(arg1:string):Promise<string>;

export function CancelDownload():Promise<void>;

export function CancelSetup():Promise<void>;

export function CheckEndpointExists(arg1:string):Promise<string|boolean>;

export function CheckForUpdatesNow():Promise<void>;

export function ClearEndpointEgressKey(arg1:string):Promise<void>;

export function ConnectMCPServer(arg1:string):Promise<void>;

export function CreateEndpoint(arg1:main.CreateEndpointRequest):Promise<string>;

export function CreatePolicyFile(arg1:string,arg2:main.NewPolicyRequest):Promise<void>;

export function DeleteDependency(arg1:string,arg2:string):Promise<void>;

export function DeleteEndpoint(arg1:string):Promise<void>;

export function DeleteEndpointMount(arg1:string,arg2:string):Promise<void>;

export function DeleteEnvironment(arg1:string,arg2:string):Promise<void>;

export function DeleteLogs(arg1:string):Promise<void>;

export function DeletePolicyFile(arg1:string,arg2:string):Promise<void>;

export function DeleteSentReview(arg1:string):Promise<void>;

export function DisconnectMCPServer(arg1:string):Promise<void>;

export function DownloadUpdate():Promise<void>;

export function EvaluatePaymentDecision(arg1:string,arg2:string,arg3:string):Promise<main.PaymentDecision>;

export function GetAggregatorURL():Promise<string>;

export function GetConfig():Promise<main.ConfigInfo>;

export function GetDefaultEndpointsPath():Promise<string>;

export function GetDependencies(arg1:string):Promise<Array<main.Dependency>>;

export function GetDownloadState():Promise<updater.DownloadState>;

export function GetEndpointDetail(arg1:string):Promise<main.EndpointDetail>;

export function GetEndpointEgressKeyStatus(arg1:string):Promise<boolean>;

export function GetEndpointMounts(arg1:string):Promise<Array<main.MountEntry>>;

export function GetEndpointSandbox(arg1:string):Promise<main.SandboxSettings>;

export function GetEndpoints():Promise<Array<main.EndpointInfo>>;

export function GetEnvironment(arg1:string):Promise<Array<main.EnvVar>>;

export function GetInstallState():Promise<updater.InstallState>;

export function GetLibraryPackages():Promise<Array<main.LibraryPackage>>;

export function GetLogDetail(arg1:string,arg2:string):Promise<main.RequestLogEntry>;

export function GetLogStats(arg1:string):Promise<main.LogStats>;

export function GetLogs(arg1:string,arg2:number,arg3:number,arg4:string):Promise<main.LogQueryResult>;

export function GetManualReviews(arg1:string,arg2:string):Promise<Array<main.ManualReviewEntry>>;

export function GetPaymentCaps():Promise<main.PaymentCapsConfig>;

export function GetPolicyFileYaml(arg1:string,arg2:string):Promise<string>;

export function GetPolicyReceipts(arg1:string,arg2:string,arg3:main.X402ReceiptFilter):Promise<main.X402ReceiptPage>;

export function GetReadme(arg1:string):Promise<string>;

export function GetRunnerCode(arg1:string):Promise<string>;

export function GetSentReviews(arg1:string):Promise<Array<main.SentReviewEntry>>;

export function GetSettings():Promise<main.Settings>;

export function GetSettingsDir():Promise<string>;

export function GetSetupSpec(arg1:string):Promise<main.SetupSpecInfo>;

export function GetSetupStatus(arg1:string):Promise<main.SetupStatusInfo>;

export function GetStatus():Promise<main.StatusInfo>;

export function GetUpdateState():Promise<updater.State>;

export function GetVersion():Promise<string>;

export function HasSettings():Promise<boolean>;

export function ImportMCPServersFromClaudeConfig():Promise<main.MCPImportResult>;

export function InstallLibraryPackage(arg1:string,arg2:string,arg3:Record<string, string>):Promise<void>;

export function InstallSkillFromPaths(arg1:string,arg2:Array<string>):Promise<void>;

export function InstallUpdate():Promise<void>;

export function ListMCPServers():Promise<Array<main.MCPServerInfo>>;

export function ListNetworkAgents():Promise<Array<main.NetworkAgentInfo>>;

export function ListPolicyFiles(arg1:string):Promise<Array<main.PolicyFileInfo>>;

export function ListSkills(arg1:string):Promise<Array<main.SkillInfo>>;

export function LogDebug(arg1:string,arg2:string):Promise<void>;

export function OpenEndpointFolder(arg1:string):Promise<void>;

export function OpenEndpointsFolder():Promise<void>;

export function OpenInDefaultApp(arg1:string):Promise<void>;

export function OpenReleaseNotes(arg1:string):Promise<void>;

export function ReadSkill(arg1:string,arg2:string):Promise<string>;

export function RecordPayment(arg1:main.PaymentRecord):Promise<void>;

export function RecordSentReview(arg1:main.SentReviewInput):Promise<void>;

export function RejectManualReview(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ReloadEndpoints():Promise<void>;

export function RemoveSkill(arg1:string,arg2:string):Promise<void>;

export function RenameEndpoint(arg1:string,arg2:string):Promise<string>;

export function ResendEmailSignIn():Promise<void>;

export function ResetPaymentCap(arg1:string):Promise<void>;

export function RespondToSetupConfirm(arg1:boolean):Promise<void>;

export function RespondToSetupPrompt(arg1:string):Promise<void>;

export function RespondToSetupSelect(arg1:string):Promise<void>;

export function RevealDownloadedUpdate(arg1:string):Promise<void>;

export function RunEndpointSetup(arg1:string,arg2:boolean):Promise<void>;

export function SaveAgentAttachment(arg1:string,arg2:string):Promise<string>;

export function SaveAttachmentAs(arg1:string,arg2:string):Promise<string>;

export function SavePolicyFileYaml(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveReadme(arg1:string,arg2:string):Promise<void>;

export function SaveRunnerCode(arg1:string,arg2:string):Promise<void>;

export function SaveSettingsData(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SendAgentMessage(arg1:string):Promise<void>;

export function SendAgentMessageWithCredential(arg1:string,arg2:string):Promise<void>;

export function SetAutoCheckEnabled(arg1:boolean):Promise<void>;

export function SetContainerEnabled(arg1:boolean):Promise<void>;

export function SetEndpointEgressKey(arg1:string,arg2:string):Promise<void>;

export function SetEndpointMount(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function SetEndpointSandbox(arg1:string,arg2:main.SandboxSettings):Promise<void>;

export function SetEnvironment(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetMCPServerEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetPaymentCap(arg1:main.PaymentCap):Promise<void>;

export function SetSentReviewNote(arg1:string,arg2:string):Promise<void>;

export function SetSentReviewStatus(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Start():Promise<void>;

export function StartAgentSession(arg1:string,arg2:string):Promise<string>;

export function StartAgentSessionWithCredential(arg1:string,arg2:string,arg3:string):Promise<string>;

export function StartAgentSessionWithHistory(arg1:string,arg2:string,arg3:string):Promise<string>;

export function StartEmailSignIn(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Stop():Promise<void>;

export function StopAgentSession():Promise<void>;

export function StopChat():Promise<void>;

export function StreamChat(arg1:main.ChatRequest):Promise<void>;

export function ToggleEndpointEnabled(arg1:string):Promise<boolean>;

export function TransactionHistory(arg1:main.TransactionFilter):Promise<main.TransactionPage>;

export function TransactionHistoryExportCSV(arg1:main.TransactionFilter):Promise<string>;

export function UpdateEndpointOverview(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function UpdateSettlement(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<void>;

export function ValidateAttachmentPath(arg1:string):Promise<main.AttachmentSummary>;

export function VerifyEmailSignIn(arg1:string):Promise<void>;

export function WalletBalance():Promise<main.WalletBalance>;

export function WalletFund():Promise<main.FundResult>;

export function WalletInit():Promise<main.WalletInfo>;

export function WalletPayChallenge(arg1:string,arg2:string,arg3:string):Promise<string>;

export function WalletShow():Promise<main.WalletInfo>;
