// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDependency(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddDependency'](arg1, arg2, arg3);
}

export function BrowseForFolder(arg1) {
  return window['go']['main']['App']['BrowseForFolder'](arg1);
}

export function CheckEndpointExists(arg1) {
  return window['go']['main']['App']['CheckEndpointExists'](arg1);
}

export function CreateEndpoint(arg1) {
  return window['go']['main']['App']['CreateEndpoint'](arg1);
}

export function CreatePolicyFile(arg1, arg2) {
  return window['go']['main']['App']['CreatePolicyFile'](arg1, arg2);
}

export function DeleteDependency(arg1, arg2) {
  return window['go']['main']['App']['DeleteDependency'](arg1, arg2);
}

export function DeleteEndpoint(arg1) {
  return window['go']['main']['App']['DeleteEndpoint'](arg1);
}

export function DeleteEnvironment(arg1, arg2) {
  return window['go']['main']['App']['DeleteEnvironment'](arg1, arg2);
}

export function DeleteLogs(arg1) {
  return window['go']['main']['App']['DeleteLogs'](arg1);
}

export function DeletePolicy(arg1, arg2) {
  return window['go']['main']['App']['DeletePolicy'](arg1, arg2);
}

export function DeletePolicyFile(arg1, arg2) {
  return window['go']['main']['App']['DeletePolicyFile'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDefaultEndpointsPath() {
  return window['go']['main']['App']['GetDefaultEndpointsPath']();
}

export function GetDependencies(arg1) {
  return window['go']['main']['App']['GetDependencies'](arg1);
}

export function GetEndpointDetail(arg1) {
  return window['go']['main']['App']['GetEndpointDetail'](arg1);
}

export function GetEndpoints() {
  return window['go']['main']['App']['GetEndpoints']();
}

export function GetEnvironment(arg1) {
  return window['go']['main']['App']['GetEnvironment'](arg1);
}

export function GetLogDetail(arg1, arg2) {
  return window['go']['main']['App']['GetLogDetail'](arg1, arg2);
}

export function GetLogStats(arg1) {
  return window['go']['main']['App']['GetLogStats'](arg1);
}

export function GetLogs(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetLogs'](arg1, arg2, arg3, arg4);
}

export function GetPolicies(arg1) {
  return window['go']['main']['App']['GetPolicies'](arg1);
}

export function GetPoliciesYaml(arg1) {
  return window['go']['main']['App']['GetPoliciesYaml'](arg1);
}

export function GetPolicyFileYaml(arg1, arg2) {
  return window['go']['main']['App']['GetPolicyFileYaml'](arg1, arg2);
}

export function GetReadme(arg1) {
  return window['go']['main']['App']['GetReadme'](arg1);
}

export function GetRunnerCode(arg1) {
  return window['go']['main']['App']['GetRunnerCode'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSettingsDir() {
  return window['go']['main']['App']['GetSettingsDir']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HasSettings() {
  return window['go']['main']['App']['HasSettings']();
}

export function ListPolicyFiles(arg1) {
  return window['go']['main']['App']['ListPolicyFiles'](arg1);
}

export function LogDebug(arg1, arg2) {
  return window['go']['main']['App']['LogDebug'](arg1, arg2);
}

export function OpenEndpointFolder(arg1) {
  return window['go']['main']['App']['OpenEndpointFolder'](arg1);
}

export function OpenEndpointsFolder() {
  return window['go']['main']['App']['OpenEndpointsFolder']();
}

export function ReloadEndpoints() {
  return window['go']['main']['App']['ReloadEndpoints']();
}

export function SavePoliciesYaml(arg1, arg2) {
  return window['go']['main']['App']['SavePoliciesYaml'](arg1, arg2);
}

export function SavePolicy(arg1, arg2) {
  return window['go']['main']['App']['SavePolicy'](arg1, arg2);
}

export function SavePolicyFileYaml(arg1, arg2, arg3) {
  return window['go']['main']['App']['SavePolicyFileYaml'](arg1, arg2, arg3);
}

export function SaveReadme(arg1, arg2) {
  return window['go']['main']['App']['SaveReadme'](arg1, arg2);
}

export function SaveRunnerCode(arg1, arg2) {
  return window['go']['main']['App']['SaveRunnerCode'](arg1, arg2);
}

export function SaveSettingsData(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSettingsData'](arg1, arg2, arg3);
}

export function SetEnvironment(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetEnvironment'](arg1, arg2, arg3);
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}

export function ToggleEndpointEnabled(arg1) {
  return window['go']['main']['App']['ToggleEndpointEnabled'](arg1);
}

export function UpdateEndpointOverview(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateEndpointOverview'](arg1, arg2, arg3, arg4, arg5);
}
