// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddDependency(arg1:string,arg2:string,arg3:string):Promise<void>;

export function BrowseForFolder(arg1:string):Promise<string>;

export function CheckEndpointExists(arg1:string):Promise<string|boolean>;

export function CreateEndpoint(arg1:main.CreateEndpointRequest):Promise<string>;

export function CreatePolicyFile(arg1:string,arg2:main.NewPolicyRequest):Promise<void>;

export function DeleteDependency(arg1:string,arg2:string):Promise<void>;

export function DeleteEndpoint(arg1:string):Promise<void>;

export function DeleteEnvironment(arg1:string,arg2:string):Promise<void>;

export function DeleteLogs(arg1:string):Promise<void>;

export function DeletePolicy(arg1:string,arg2:string):Promise<void>;

export function DeletePolicyFile(arg1:string,arg2:string):Promise<void>;

export function GetConfig():Promise<main.ConfigInfo>;

export function GetDefaultEndpointsPath():Promise<string>;

export function GetDependencies(arg1:string):Promise<Array<main.Dependency>>;

export function GetEndpointDetail(arg1:string):Promise<main.EndpointDetail>;

export function GetEndpoints():Promise<Array<main.EndpointInfo>>;

export function GetEnvironment(arg1:string):Promise<Array<main.EnvVar>>;

export function GetLogDetail(arg1:string,arg2:string):Promise<main.RequestLogEntry>;

export function GetLogStats(arg1:string):Promise<main.LogStats>;

export function GetLogs(arg1:string,arg2:number,arg3:number,arg4:string):Promise<main.LogQueryResult>;

export function GetPolicies(arg1:string):Promise<Array<main.Policy>>;

export function GetPoliciesYaml(arg1:string):Promise<string>;

export function GetPolicyFileYaml(arg1:string,arg2:string):Promise<string>;

export function GetReadme(arg1:string):Promise<string>;

export function GetRunnerCode(arg1:string):Promise<string>;

export function GetSettings():Promise<main.Settings>;

export function GetSettingsDir():Promise<string>;

export function GetStatus():Promise<main.StatusInfo>;

export function GetVersion():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function HasSettings():Promise<boolean>;

export function ListPolicyFiles(arg1:string):Promise<Array<main.PolicyFileInfo>>;

export function LogDebug(arg1:string,arg2:string):Promise<void>;

export function OpenEndpointFolder(arg1:string):Promise<void>;

export function OpenEndpointsFolder():Promise<void>;

export function ReloadEndpoints():Promise<void>;

export function SavePoliciesYaml(arg1:string,arg2:string):Promise<void>;

export function SavePolicy(arg1:string,arg2:main.Policy):Promise<void>;

export function SavePolicyFileYaml(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveReadme(arg1:string,arg2:string):Promise<void>;

export function SaveRunnerCode(arg1:string,arg2:string):Promise<void>;

export function SaveSettingsData(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetEnvironment(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Start():Promise<void>;

export function Stop():Promise<void>;

export function ToggleEndpointEnabled(arg1:string):Promise<boolean>;

export function UpdateEndpointOverview(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;
