// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDependency(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddDependency'](arg1, arg2, arg3);
}

export function ApplyHostResolution(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ApplyHostResolution'](arg1, arg2, arg3, arg4);
}

export function ApplyHostResolutionDetailed(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ApplyHostResolutionDetailed'](arg1, arg2, arg3, arg4);
}

export function ApproveManualReview(arg1, arg2) {
  return window['go']['main']['App']['ApproveManualReview'](arg1, arg2);
}

export function AttachToActiveSession(arg1) {
  return window['go']['main']['App']['AttachToActiveSession'](arg1);
}

export function AttachmentInlineBytes(arg1, arg2) {
  return window['go']['main']['App']['AttachmentInlineBytes'](arg1, arg2);
}

export function BrowseForAttachment() {
  return window['go']['main']['App']['BrowseForAttachment']();
}

export function BrowseForFolder(arg1) {
  return window['go']['main']['App']['BrowseForFolder'](arg1);
}

export function BrowseForSkillFile(arg1) {
  return window['go']['main']['App']['BrowseForSkillFile'](arg1);
}

export function CancelDownload() {
  return window['go']['main']['App']['CancelDownload']();
}

export function CancelSetup() {
  return window['go']['main']['App']['CancelSetup']();
}

export function CheckEndpointExists(arg1) {
  return window['go']['main']['App']['CheckEndpointExists'](arg1);
}

export function CheckForUpdatesNow() {
  return window['go']['main']['App']['CheckForUpdatesNow']();
}

export function CreateEndpoint(arg1) {
  return window['go']['main']['App']['CreateEndpoint'](arg1);
}

export function CreatePolicyFile(arg1, arg2) {
  return window['go']['main']['App']['CreatePolicyFile'](arg1, arg2);
}

export function DeleteDependency(arg1, arg2) {
  return window['go']['main']['App']['DeleteDependency'](arg1, arg2);
}

export function DeleteEndpoint(arg1) {
  return window['go']['main']['App']['DeleteEndpoint'](arg1);
}

export function DeleteEnvironment(arg1, arg2) {
  return window['go']['main']['App']['DeleteEnvironment'](arg1, arg2);
}

export function DeleteLogs(arg1) {
  return window['go']['main']['App']['DeleteLogs'](arg1);
}

export function DeletePolicyFile(arg1, arg2) {
  return window['go']['main']['App']['DeletePolicyFile'](arg1, arg2);
}

export function DeleteSentReview(arg1) {
  return window['go']['main']['App']['DeleteSentReview'](arg1);
}

export function DownloadUpdate() {
  return window['go']['main']['App']['DownloadUpdate']();
}

export function EvaluatePaymentDecision(arg1, arg2, arg3) {
  return window['go']['main']['App']['EvaluatePaymentDecision'](arg1, arg2, arg3);
}

export function GetAggregatorURL() {
  return window['go']['main']['App']['GetAggregatorURL']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDefaultEndpointsPath() {
  return window['go']['main']['App']['GetDefaultEndpointsPath']();
}

export function GetDependencies(arg1) {
  return window['go']['main']['App']['GetDependencies'](arg1);
}

export function GetDownloadState() {
  return window['go']['main']['App']['GetDownloadState']();
}

export function GetEndpointDetail(arg1) {
  return window['go']['main']['App']['GetEndpointDetail'](arg1);
}

export function GetEndpoints() {
  return window['go']['main']['App']['GetEndpoints']();
}

export function GetEnvironment(arg1) {
  return window['go']['main']['App']['GetEnvironment'](arg1);
}

export function GetInstallState() {
  return window['go']['main']['App']['GetInstallState']();
}

export function GetLibraryPackages() {
  return window['go']['main']['App']['GetLibraryPackages']();
}

export function GetLogDetail(arg1, arg2) {
  return window['go']['main']['App']['GetLogDetail'](arg1, arg2);
}

export function GetLogStats(arg1) {
  return window['go']['main']['App']['GetLogStats'](arg1);
}

export function GetLogs(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetLogs'](arg1, arg2, arg3, arg4);
}

export function GetManualReviews(arg1, arg2) {
  return window['go']['main']['App']['GetManualReviews'](arg1, arg2);
}

export function GetPaymentCaps() {
  return window['go']['main']['App']['GetPaymentCaps']();
}

export function GetPolicyFileYaml(arg1, arg2) {
  return window['go']['main']['App']['GetPolicyFileYaml'](arg1, arg2);
}

export function GetPolicyReceipts(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetPolicyReceipts'](arg1, arg2, arg3);
}

export function GetReadme(arg1) {
  return window['go']['main']['App']['GetReadme'](arg1);
}

export function GetRunnerCode(arg1) {
  return window['go']['main']['App']['GetRunnerCode'](arg1);
}

export function GetSentReviews(arg1) {
  return window['go']['main']['App']['GetSentReviews'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSettingsDir() {
  return window['go']['main']['App']['GetSettingsDir']();
}

export function GetSetupSpec(arg1) {
  return window['go']['main']['App']['GetSetupSpec'](arg1);
}

export function GetSetupStatus(arg1) {
  return window['go']['main']['App']['GetSetupStatus'](arg1);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetUpdateState() {
  return window['go']['main']['App']['GetUpdateState']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function HasSettings() {
  return window['go']['main']['App']['HasSettings']();
}

export function InstallLibraryPackage(arg1, arg2, arg3) {
  return window['go']['main']['App']['InstallLibraryPackage'](arg1, arg2, arg3);
}

export function InstallSkillFromPaths(arg1, arg2) {
  return window['go']['main']['App']['InstallSkillFromPaths'](arg1, arg2);
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function ListNetworkAgents() {
  return window['go']['main']['App']['ListNetworkAgents']();
}

export function ListPolicyFiles(arg1) {
  return window['go']['main']['App']['ListPolicyFiles'](arg1);
}

export function ListSkills(arg1) {
  return window['go']['main']['App']['ListSkills'](arg1);
}

export function LogDebug(arg1, arg2) {
  return window['go']['main']['App']['LogDebug'](arg1, arg2);
}

export function OpenEndpointFolder(arg1) {
  return window['go']['main']['App']['OpenEndpointFolder'](arg1);
}

export function OpenEndpointsFolder() {
  return window['go']['main']['App']['OpenEndpointsFolder']();
}

export function OpenInDefaultApp(arg1) {
  return window['go']['main']['App']['OpenInDefaultApp'](arg1);
}

export function OpenReleaseNotes(arg1) {
  return window['go']['main']['App']['OpenReleaseNotes'](arg1);
}

export function ReadSkill(arg1, arg2) {
  return window['go']['main']['App']['ReadSkill'](arg1, arg2);
}

export function RecordPayment(arg1) {
  return window['go']['main']['App']['RecordPayment'](arg1);
}

export function RecordSentReview(arg1) {
  return window['go']['main']['App']['RecordSentReview'](arg1);
}

export function RejectManualReview(arg1, arg2, arg3) {
  return window['go']['main']['App']['RejectManualReview'](arg1, arg2, arg3);
}

export function ReloadEndpoints() {
  return window['go']['main']['App']['ReloadEndpoints']();
}

export function RemoveSkill(arg1, arg2) {
  return window['go']['main']['App']['RemoveSkill'](arg1, arg2);
}

export function RenameEndpoint(arg1, arg2) {
  return window['go']['main']['App']['RenameEndpoint'](arg1, arg2);
}

export function ResetPaymentCap(arg1) {
  return window['go']['main']['App']['ResetPaymentCap'](arg1);
}

export function RespondToSetupConfirm(arg1) {
  return window['go']['main']['App']['RespondToSetupConfirm'](arg1);
}

export function RespondToSetupPrompt(arg1) {
  return window['go']['main']['App']['RespondToSetupPrompt'](arg1);
}

export function RespondToSetupSelect(arg1) {
  return window['go']['main']['App']['RespondToSetupSelect'](arg1);
}

export function RevealDownloadedUpdate(arg1) {
  return window['go']['main']['App']['RevealDownloadedUpdate'](arg1);
}

export function RunEndpointSetup(arg1, arg2) {
  return window['go']['main']['App']['RunEndpointSetup'](arg1, arg2);
}

export function SaveAgentAttachment(arg1, arg2) {
  return window['go']['main']['App']['SaveAgentAttachment'](arg1, arg2);
}

export function SaveAttachmentAs(arg1, arg2) {
  return window['go']['main']['App']['SaveAttachmentAs'](arg1, arg2);
}

export function SavePolicyFileYaml(arg1, arg2, arg3) {
  return window['go']['main']['App']['SavePolicyFileYaml'](arg1, arg2, arg3);
}

export function SaveReadme(arg1, arg2) {
  return window['go']['main']['App']['SaveReadme'](arg1, arg2);
}

export function SaveRunnerCode(arg1, arg2) {
  return window['go']['main']['App']['SaveRunnerCode'](arg1, arg2);
}

export function SaveSettingsData(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSettingsData'](arg1, arg2, arg3);
}

export function SendAgentMessage(arg1) {
  return window['go']['main']['App']['SendAgentMessage'](arg1);
}

export function SendAgentMessageWithCredential(arg1, arg2) {
  return window['go']['main']['App']['SendAgentMessageWithCredential'](arg1, arg2);
}

export function SetAutoCheckEnabled(arg1) {
  return window['go']['main']['App']['SetAutoCheckEnabled'](arg1);
}

export function SetContainerEnabled(arg1) {
  return window['go']['main']['App']['SetContainerEnabled'](arg1);
}

export function SetEnvironment(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetEnvironment'](arg1, arg2, arg3);
}

export function SetPaymentCap(arg1) {
  return window['go']['main']['App']['SetPaymentCap'](arg1);
}

export function SetSentReviewNote(arg1, arg2) {
  return window['go']['main']['App']['SetSentReviewNote'](arg1, arg2);
}

export function SetSentReviewStatus(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetSentReviewStatus'](arg1, arg2, arg3);
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function StartAgentSession(arg1, arg2) {
  return window['go']['main']['App']['StartAgentSession'](arg1, arg2);
}

export function StartAgentSessionWithCredential(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartAgentSessionWithCredential'](arg1, arg2, arg3);
}

export function StartAgentSessionWithHistory(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartAgentSessionWithHistory'](arg1, arg2, arg3);
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}

export function StopAgentSession() {
  return window['go']['main']['App']['StopAgentSession']();
}

export function StopChat() {
  return window['go']['main']['App']['StopChat']();
}

export function StreamChat(arg1) {
  return window['go']['main']['App']['StreamChat'](arg1);
}

export function ToggleEndpointEnabled(arg1) {
  return window['go']['main']['App']['ToggleEndpointEnabled'](arg1);
}

export function TransactionHistory(arg1) {
  return window['go']['main']['App']['TransactionHistory'](arg1);
}

export function TransactionHistoryExportCSV(arg1) {
  return window['go']['main']['App']['TransactionHistoryExportCSV'](arg1);
}

export function UpdateEndpointOverview(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateEndpointOverview'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateSettlement(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateSettlement'](arg1, arg2, arg3, arg4, arg5);
}

export function ValidateAttachmentPath(arg1) {
  return window['go']['main']['App']['ValidateAttachmentPath'](arg1);
}

export function WalletBalance() {
  return window['go']['main']['App']['WalletBalance']();
}

export function WalletFund() {
  return window['go']['main']['App']['WalletFund']();
}

export function WalletInit() {
  return window['go']['main']['App']['WalletInit']();
}

export function WalletPayChallenge(arg1, arg2, arg3) {
  return window['go']['main']['App']['WalletPayChallenge'](arg1, arg2, arg3);
}

export function WalletShow() {
  return window['go']['main']['App']['WalletShow']();
}
