name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["type: enhancement", "status: needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide details below.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component should this feature be added to?
      options:
        - Backend (FastAPI/Python)
        - Frontend (React/TypeScript)
        - Python SDK
        - TypeScript SDK
        - Database
        - Authentication
        - DevOps/Deployment
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a problem?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: Describe any alternative solutions or features you've considered

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: Who would benefit from this feature and how?
      placeholder: |
        - Users would be able to...
        - This would improve...
        - It would make it easier to...

  - type: textarea
    id: examples
    attributes:
      label: Code Examples or Mockups
      description: If applicable, provide code examples or mockups of how this feature would work
      placeholder: |
        ```python
        # Example usage
        client.new_feature.do_something()
        ```
      render: markdown

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Any additional information

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have clearly described the problem this feature would solve
          required: true
        - label: I am willing to help implement this feature (optional)
          required: false
